"""initial agent state schema

Revision ID: c1357bf15f54
Revises: 
Create Date: 2026-08-12 15:41:03.124915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1357bf15f54'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idempotency_key', sa.String(length=128), nullable=True))
        batch_op.alter_column('last_heartbeat_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('stale_detected_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_agent_runs_last_heartbeat_at'), ['last_heartbeat_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_runtime_id'), ['runtime_id'], unique=False)
        batch_op.create_unique_constraint('uq_agent_run_user_idempotency_key', ['user_id', 'idempotency_key'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_constraint('uq_agent_run_user_idempotency_key', type_='unique')
        batch_op.drop_index(batch_op.f('ix_agent_runs_runtime_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_last_heartbeat_at'))
        batch_op.alter_column('stale_detected_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('last_heartbeat_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.drop_column('idempotency_key')

    # ### end Alembic commands ###
